name: Deploy to Virtual Machine

on: [push]

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Copy deploy files to VM
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "minio,mlflow,docker-compose.yml"
        target: ~/infrastructure/

    - name: Run MLFlow
      uses: appleboy/ssh-action@v1.0.3
      env:
        MINIO_USER: ${{ secrets.MINIO_USER }}
        MINIO_PASSWORD: ${{ secrets.MINIO_PASSWORD }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      with:
        host: ${{ secrets.SSH_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        envs: MINIO_USER,MINIO_PASSWORD,POSTGRES_USER,POSTGRES_PASSWORD
        script: |
          docker compose -f infrastructure/docker-compose.yml up -d
